version: "3.8"
services:
  p2p_node1:
    build:
      context: .
      dockerfile: Dockerfile
    stdin_open: true
    tty: true
    cap_add:
      - NET_ADMIN
    ports:
      - "12346:8080/tcp"
      - "12345:12346/udp"
    volumes:
      - ./node1_data:/app/downloads
      - ./node1_shared:/app/shared
      - ./logs:/app/logs
    command:
      [
        "/bin/sh",
        "-c",
        "/app/p2p_resource_sync_app 1 12346 12345 8080 1 /app/downloads 2>> /app/logs/diagnostic.log",
      ]
    networks:
      - p2p_network

  p2p_node2:
    build:
      context: .
      dockerfile: Dockerfile
    stdin_open: true
    tty: true
    cap_add:
      - NET_ADMIN
    ports:
      - "12348:8080/tcp"
      - "12347:12346/udp"
    volumes:
      - ./node2_data:/app/downloads
      - ./node2_shared:/app/shared
      - ./logs:/app/logs
    command:
      [
        "/bin/sh",
        "-c",
        "/app/p2p_resource_sync_app 2 12346 12345 8080 1 /app/downloads 2>> /app/logs/diagnostic.log",
      ]
    networks:
      - p2p_network

  p2p_node3:
    build:
      context: .
      dockerfile: Dockerfile
    stdin_open: true
    tty: true
    cap_add:
      - NET_ADMIN
    ports:
      - "12350:8080/tcp"
      - "12349:12346/udp"
    volumes:
      - ./node3_data:/app/downloads
      - ./node3_shared:/app/shared
      - ./logs:/app/logs
    command:
      [
        "/bin/sh",
        "-c",
        "/app/p2p_resource_sync_app 3 12346 12345 8080 1 /app/downloads 2>> /app/logs/diagnostic.log",
      ]
    networks:
      - p2p_network

networks:
  p2p_network:
    driver: bridge
